In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sqlite3

In [4]:
conn = sqlite3.connect('data/sakila.db')

df = pd.read_sql('SELECT * FROM rental', conn)

In [5]:
df.head()

rental_id              rental_date  inventory_id  customer_id  \
0          1  2005-05-24 22:53:30.000           367          130   
1          2  2005-05-24 22:54:33.000          1525          459   
2          3  2005-05-24 23:03:39.000          1711          408   
3          4  2005-05-24 23:04:41.000          2452          333   
4          5  2005-05-24 23:05:21.000          2079          222   

               return_date  staff_id          last_update  
0  2005-05-26 22:04:30.000         1  2019-04-11 18:11:49  
1  2005-05-28 19:40:33.000         1  2019-04-11 18:11:49  
2  2005-06-01 22:12:39.000         1  2019-04-11 18:11:49  
3  2005-06-03 01:43:41.000         2  2019-04-11 18:11:49  
4  2005-06-02 04:33:21.000         1  2019-04-11 18:11:49

In [6]:
df.describe()

rental_id  inventory_id   customer_id      staff_id
count  16044.000000  16044.000000  16044.000000  16044.000000
mean    8025.371478   2291.842558    297.143169      1.498878
std     4632.777249   1322.210643    172.453136      0.500014
min        1.000000      1.000000      1.000000      1.000000
25%     4013.750000   1154.000000    148.000000      1.000000
50%     8025.500000   2291.000000    296.000000      1.000000
75%    12037.250000   3433.000000    446.000000      2.000000
max    16049.000000   4581.000000    599.000000      2.000000

In [12]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:2, :2])

[['a' 'b']
 ['d' 'e']]


In [14]:
a = np.arange(5)
print(a)
a + 20

[0 1 2 3 4]


array([20, 21, 22, 23, 24])

In [15]:
a = np.arange(5)

print(a <= 3)

[ True  True  True  True False]


In [23]:
import pandas as pd

certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)

print(certificates_earned)

Tom      8
Kris     2
Ahmad    5
Beau     6
dtype: int64


In [25]:
certificates_earned.values

array([8, 2, 5, 6])

In [26]:
import pandas as pd

certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)

print(certificates_earned[certificates_earned > 5])

Tom     8
Beau    6
dtype: int64


In [35]:
import pandas as pd

certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})

certificates_earned.index = ['Tom', 'Kris', 'Ahmad', 'Beau']

certificates_earned.describe()

#print(certificates_earned)

#print(certificates_earned.iloc[2])

Certificates  Time (in months)
count          4.00          4.000000
mean           5.25         10.500000
std            2.50          4.654747
min            2.00          5.000000
25%            4.25          8.000000
50%            5.50         10.500000
75%            6.50         13.000000
max            8.00         16.000000

In [44]:
import pandas as pd

certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})
names = ['Tom', 'Kris', 'Ahmad', 'Beau']

certificates_earned.index = names
longest_streak = pd.Series([13, 11, 9, 7], index=names)
certificates_earned['Longest streak'] = longest_streak

certificates_earned = certificates_earned.drop('Tom')

print(certificates_earned)

       Certificates  Time (in months)  Longest streak
Kris              2                 5              11
Ahmad             5                 9               9
Beau              6                12               7


In [47]:
import pandas as pd

certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})
names = ['Tom', 'Kris', 'Ahmad', 'Beau']

certificates_earned.index = names
certificates_earned['Certificates per month'] = round(certificates_earned['Certificates'] / certificates_earned['Time (in months)'], 2)

print(certificates_earned)

       Certificates  Time (in months)  Certificates per month
Tom               8                16                    0.50
Kris              2                 5                    0.40
Ahmad             5                 9                    0.56
Beau              6                12                    0.50


In [54]:
import pandas as pd
import numpy as np

s = pd.Series(['a', 3, np.nan, 1, np.nan])

print(s.isnull().sum())

2


In [56]:
import pandas as pd
import numpy as np

s = pd.Series([np.nan, 1, 2, np.nan, 3])
s = s.fillna(method='bfill')

print(s)

0    1.0
1    1.0
2    2.0
3    3.0
4    3.0
dtype: float64


/var/folders/_m/kxv31bnn2kg5ktcpnch3gpjr0000gn/T/ipykernel_31256/2973901440.py:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s = s.fillna(method='bfill')


In [58]:
import csv

with open('certificates.csv', 'r') as fp:
    reader = csv.reader(fp, delimiter='$')
    next(reader)
    for index, values in enumerate(reader):
        name, certs_num, months_num = values
        print(f"{name} earned {certs_num} certificates in {months_num} months")

Tom earned 8 certificates in 16 months
Kris earned 2 certificates in 5 months
Ahmad earned 5 certificates in 9 months
Beau earned 6 certificates in 12 months


In [60]:
import pandas as pd
df = pd.read_csv("certificates.csv", delimiter='$')

df.head()

Name  Certificates  Time (in months)
0    Tom             8                16
1   Kris             2                 5
2  Ahmad             5                 9
3   Beau             6                12

In [6]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('chinook.db')

cur = conn.cursor()

cur.execute('SELECT * FROM employees;')

OperationalError: no such table: employees